package com.event.reminder.constant

enum class NavigationConstant {

    LOGIN_SCREEN,
    SPLASH_TO_LOGIN_SCREEN,
    SIGN_UP_SCREEN,
    FORGET_PASSWORD_SCREEN,
    PROFILE_SCREEN,
    SIGN_UP_TO_OTP_SCREEN,
    PROFILE_TO_OTP_SCREEN,
    DASHBOARD_SCREEN,
    SPLASH_TO_DASHBOARD_SCREEN
}